services:

  # Ejemplo de microservicio (cada equipo agrega el suyo copiando este bloque)
  medicamentos:
    build: ./services/medicamentos
    environment:
      - PORT=8080
    networks:
      - cuidabien-net
    ports:
      - "8081:8080"

  alimentacion:
    build: ./services/alimentacion
    environment:
      - PORT=8080
    networks:
      - cuidabien-net
    ports:
      - "8084:8080"

  informacion-salud:
    build: ./services/informacion-salud
    environment:
      - PORT=8080
    networks:
      - cuidabien-net
    ports:
      - "8082:8080"

  citas:
    build: ./services/citas
    environment:
      - PORT=8080
      - INFORMACION_SALUD_URL=http://informacion-salud:8080
    networks:
      - cuidabien-net
    depends_on:
      - informacion-salud
    ports:
      - "8085:8080"

  reportes:
    build: ./services/reportes
    environment:
      - PORT=8080
      - CITAS_URL=http://citas:8080
      - MEDICAMENTOS_URL=http://medicamentos:8080
      - ALIMENTACION_URL=http://alimentacion:8080
    depends_on:
      - citas
      - medicamentos
      - alimentacion
    networks:
      - cuidabien-net
    ports:
      - "8088:8080"

  estado-animo:
    build: ./services/estado-animo
    environment:
      - PORT=8080
    networks:
      - cuidabien-net
    ports:
      - "8087:8080"

  reportes-medicos:
    build: ./services/reportes-medicos
    environment:
      - PORT=8080
      - CITAS_URL=http://citas:8080
    networks:
      - cuidabien-net
    ports:
      - "8086:8080"

  gateway:
    build: ./services/gateway
    environment:
      - PORT=8080
      - MEDICAMENTOS_URL=http://medicamentos:8080
      - CITAS_URL=http://citas:8080
      - REPORTES_URL=http://reportes:8080
      - ALIMENTACION_URL=http://alimentacion:8080
      - INFORMACION_SALUD_URL=http://informacion-salud:8080
      - ESTADO_ANIMO_URL=http://estado-animo:8080
      - REPORTES_MEDICOS_URL=http://reportes-medicos:8080
      # Aquí se van agregando las URLs de los demás servicios:
      # - EMERGENCIA_URL=http://emergencia:8080
      # - MONITOREO_URL=http://monitoreo:8080
    depends_on:
      - medicamentos
      - citas
      - reportes
      - alimentacion
      - informacion-salud
      - estado-animo
      - reportes-medicos
    networks:
      - cuidabien-net
    ports:
      - "8080:8080"

networks:
  cuidabien-net:
    driver: bridge
