name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - medicamentos
          - emergencia
          - monitoreo
          - gateway
          # agregar aquí cada nuevo microservicio

    defaults:
      run:
        working-directory: ./services/${{ matrix.service }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: services/${{ matrix.service }}/go.sum

      - name: Descargar dependencias
        run: go mod download

      - name: go vet
        run: go vet ./...

      - name: go build
        run: go build ./...

      - name: go test
        run: go test ./... -v